### ISSUE TITLE
Mounts can be defined but mount point will not be created

### ISSUE THREAD

**Issue by robertdebock** [covermymeds/puppet-gluster#16]
When defining a mount, like so:

```
gluster_mounts:
  /somemountpoint:
    volume: host:/somevolume
    ensure: mounted
    options: defaults
```

The mount point (in this case /somemountpoint) will not be created.

Is that expected behaviour? (I was hoping it would also ensure the mount point is a directory.)
